### ISSUE TITLE
Should I create dispatcher for every player in  the room ?

### ISSUE THREAD

**Issue by zgz682000** [colyseus/command#1]
Dispatcher will forcus cmds to execute in a queue. If I create single dispatcher for one room,  dose it probabily block other players' cmds handling when one player's cmd awaiting ? So I am considering if it's necessary create dispatcher for every player in the room.

If all cmds are sync, is there no difference between single dispatcher mode and one-player-one-dispatcher mode, because of Node.js's single thread mechanism?

How should I judge how many dispatcher instance to create for one room

**Comment by endel** [comment]
Hi @zgz682000, I think that's not necessary. Each `.dispatch()` call will create its own command queue if necessary, you should be able to have multiple queues running at the same time. Let me know if you find any problems with it!

**Comment by zgz682000** [comment]
Oh, it’s my mistake. I am sorry for didn’t seriously read the source code
